[workspace]
members = ["crates/*"]
resolver = "2"
default-members = ["crates/sunbot"]

[workspace.dependencies]
serenity = "0.12.2"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.14"
poise = "0.6.1"
once_cell = "1.19.0"
tracing = "0.1"
tracing-subscriber = "0.3.18"
sysinfo = "0.30.12"
humantime = "2.1"
regex = "1.10"
lazy_static = "1.5"
rand = "0.8"