//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guild")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub joined_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::punishment::Entity")]
    Punishment,
    #[sea_orm(has_one = "super::punishment_channel::Entity")]
    PunishmentChannel,
    #[sea_orm(has_many = "super::punishment_song::Entity")]
    PunishmentSong,
}

impl Related<super::punishment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Punishment.def()
    }
}

impl Related<super::punishment_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PunishmentChannel.def()
    }
}

impl Related<super::punishment_song::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PunishmentSong.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
