---
name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote images
        env:
          REPOSITORY: ghcr.io
          PROJECT: aaronfoley
          IMAGE_NAME: sunbot-rs
          GITHUB_SHA: ${{ github.sha }}
        run: |
          export IMAGE="${REPOSITORY}/${PROJECT}/${IMAGE_NAME,,}" \
          && echo "Promoting image $IMAGE:sha-${GITHUB_SHA::7} to $IMAGE:${{ github.ref_name }}" \
          && docker pull $IMAGE:sha-${GITHUB_SHA::7} \
          && docker tag $IMAGE:sha-${GITHUB_SHA::7} $IMAGE:${{ github.ref_name }} \
          && docker push $IMAGE:${{ github.ref_name }}
        # The following works with a PAT, but not with GITHUB_TOKEN
        #  && docker buildx imagetools create $IMAGE:sha-${GITHUB_SHA::7} \
        #    --tag $IMAGE:${{ github.ref_name }}
