---
name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote images
        env:
          REPOSITORY: https://ghcr.io
          PROJECT: aaronfoley
          IMAGE_NAME: sunbot-rs
        run: |
          IMAGE="${REPOSITORY}/${PROJECT}/${IMAGE_NAME,,}"
          docker buildx imagetools create $IMAGE:${{ github.sha }} \
            --tag $IMAGE:${{ github.ref_name }}
